#!/usr/bin/env bash

if [ ! -f install ]; then
echo 'install must be run within its container folder' 1>&2
exit 1
fi


CURDIR=`pwd`
OLDGOPATH="$GOPATH"
export GOPATH="$CURDIR:$OLDGOPATH"

#OLDGOROOT="$GOROOT"
#export GOROOT="$CURDIR"

gofmt -w src
go install smsdemo

export GOPATH="$OLDGOPATH"
#export GOROOT="$OLDGOROOT"

echo 'finished'
